In [1]:
import numpy as np
import matplotlib as plt


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([[4],[5],[6]])
print(arr1.shape)
print(arr2.shape)
res = arr1+arr2
print(res)

(3,)
(3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [8]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([4,5,6])
print(arr1.shape)
print(arr2.shape)
res = arr1*arr2
print(res)

(2, 2)
(3,)


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 